#!/usr/bin/env python3
"""Minimal CLI helper for maintaining an OKF v0.2 note bundle.

Usage:
    python okf_notes.py init [directory] --name "My Notes"
    python okf_notes.py lfs-setup [directory]
    python okf_notes.py new topics/backpropagation.md --title "Backpropagation"
    python okf_notes.py link topics/backpropagation.md --to topics/neural-networks.md
    python okf_notes.py attach topics/backpropagation.md --file gradient.png --caption "Gradient flow"
    python okf_notes.py index --regenerate
    python okf_notes.py check
    python okf_notes.py log "Created backpropagation note" --dir topics
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    import yaml

    # Keep ISO 8601 timestamps as strings so round-tripping preserves
    # the original formatting (e.g. 2026-08-26T14:00:00Z).
    def _str_timestamp(loader: yaml.SafeLoader, node: yaml.Node) -> str:
        return str(loader.construct_scalar(node))

    yaml.SafeLoader.add_constructor("tag:yaml.org,2002:timestamp", _str_timestamp)
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore[assignment]


ACTOR = "kimi-code-cli"
RESERVED = {"index.md", "log.md"}

# File patterns routed through Git LFS when LFS support is enabled.
LFS_PATTERNS = [
    "assets/**/*.png",
    "assets/**/*.jpg",
    "assets/**/*.jpeg",
    "assets/**/*.gif",
    "assets/**/*.webp",
    "assets/**/*.svg",
    "assets/**/*.mp4",
    "assets/**/*.mov",
    "assets/**/*.webm",
    "assets/**/*.pdf",
    "assets/**/*.zip",
]
LFS_ATTRIBUTES_HEADER = (
    "# Auto-generated by okf_notes.py\n"
    "# Route large media files in assets/ through Git LFS.\n"
)


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# YAML indicator characters that may not start a plain scalar, plus the
# flow-collection separators that are unsafe inside `[...]` / `{...}`.
_YAML_INDICATORS = set("-?:,[]{}#&*!|>'\"%@`")
_YAML_WORDS = {"null", "~", "true", "false", "yes", "no", "on", "off"}


def yaml_scalar(value: Any) -> str:
    """Render a value as a safe YAML scalar without requiring PyYAML.

    Strings stay plain when unambiguous; anything risky (indicators, flow
    separators, ``": "``, ``" #"``, newlines, bool/null lookalikes, numbers)
    is double-quoted with escaping.
    """
    s = str(value)
    if (
        s
        and s == s.strip()
        and s[0] not in _YAML_INDICATORS
        and ": " not in s
        and " #" not in s
        and not any(ch in s for ch in "[]{},\n\t")
        and s.lower() not in _YAML_WORDS
        and not re.fullmatch(r"[-+]?(\d+(\.\d*)?|\.\d+)", s)
    ):
        return s
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def require_yaml() -> None:
    if yaml is None:
        print(
            "PyYAML is required for this command. Install it with:\n"
            "  pip install pyyaml\n"
            "or activate the project virtual environment.",
            file=sys.stderr,
        )
        sys.exit(1)


def is_concept(path: Path) -> bool:
    return path.suffix == ".md" and path.name not in RESERVED


def split_frontmatter(text: str) -> tuple[dict[str, Any] | None, str]:
    """Return (frontmatter_dict, body). If no frontmatter, return (None, text)."""
    require_yaml()
    if not text.startswith("---"):
        return None, text
    parts = text.split("---", 2)
    if len(parts) < 3:
        return None, text
    try:
        meta = yaml.safe_load(parts[1]) or {}
    except yaml.YAMLError:
        return None, text
    return meta, parts[2].lstrip("\n")


def build_concept(
    concept_type: str,
    title: str,
    description: str = "",
    tags: list[str] | None = None,
) -> tuple[str, dict[str, Any]]:
    tags = tags or []
    tags_yaml = "[" + ", ".join(yaml_scalar(t) for t in tags) + "]"
    desc = description or title
    meta: dict[str, Any] = {
        "type": concept_type,
        "title": title,
        "description": desc,
        "tags": tags,
        "status": "draft",
        "generated": {"by": ACTOR, "at": now_iso()},
    }
    content = f"""---
type: {yaml_scalar(concept_type)}
title: {yaml_scalar(title)}
description: {yaml_scalar(desc)}
tags: {tags_yaml}
status: draft
generated: {{ by: {yaml_scalar(ACTOR)}, at: {yaml_scalar(now_iso())} }}
---

# Summary

"""
    return content, meta


def ensure_log_entry(log_path: Path, message: str, date: str | None = None) -> None:
    """Append a dated entry to a log.md file."""
    date = date or now_iso()[:10]
    header = "# Update Log\n\n"
    if log_path.exists():
        text = log_path.read_text(encoding="utf-8")
    else:
        text = header

    # Ensure header exists
    if not text.startswith("#"):
        text = header + text

    # Insert new date section at the top if not present
    date_heading = f"## {date}"
    if date_heading not in text:
        text = text.replace(header, f"{header}{date_heading}\n", 1)

    lines = text.splitlines()
    insert_idx = len(lines)
    for i, line in enumerate(lines):
        if line == date_heading:
            insert_idx = i + 1
            break

    # Find next date heading to avoid appending under wrong date
    for j in range(insert_idx, len(lines)):
        if lines[j].startswith("## ") and lines[j] != date_heading:
            insert_idx = j
            break

    lines.insert(insert_idx, f"* {message}")
    log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def update_index(index_path: Path, title: str, rel_path: str, description: str) -> None:
    """Add or update an entry in an index.md."""
    entry = f"* [{title}]({rel_path}) - {description}\n"
    if index_path.exists():
        text = index_path.read_text(encoding="utf-8")
        # Avoid duplicate entries: match the exact link target, not substrings.
        if re.search(r"\]\(" + re.escape(rel_path) + r"\)", text):
            return
    else:
        text = f"# {index_path.parent.name or 'Index'}\n\n"
    text += entry
    index_path.write_text(text, encoding="utf-8")


def relative_to_log(log_path: Path, concept_path: Path) -> str:
    """Return a path from the log file to the concept file."""
    return Path(
        concept_path.relative_to(log_path.parent.parent)
    ).as_posix()


def cmd_new(args: argparse.Namespace) -> int:
    path = Path(args.path)
    if path.exists():
        print(f"error: file already exists: {path}", file=sys.stderr)
        return 1
    path.parent.mkdir(parents=True, exist_ok=True)
    content, meta = build_concept(
        concept_type=args.type or "Note",
        title=args.title or path.stem.replace("-", " ").replace("_", " ").title(),
        description=args.description or "",
        tags=args.tags or [],
    )
    path.write_text(content, encoding="utf-8")
    print(f"created: {path}")

    # Update index
    index_path = path.parent / "index.md"
    update_index(
        index_path,
        title=meta["title"],
        rel_path=path.name,
        description=meta.get("description", ""),
    )
    print(f"updated: {index_path}")

    # Update log
    log_path = path.parent / "log.md"
    if not log_path.exists() and path.parent != Path("."):
        log_path = Path("log.md")
    ensure_log_entry(
        log_path,
        f"**Creation**: Added [{meta['title']}]({relative_to_log(log_path, path)}).",
    )
    print(f"updated: {log_path}")
    return 0


def cmd_link(args: argparse.Namespace) -> int:
    require_yaml()
    source = Path(args.from_path)
    target = Path(args.to)
    if not source.exists():
        print(f"error: source does not exist: {source}", file=sys.stderr)
        return 1

    text = source.read_text(encoding="utf-8")
    meta, body = split_frontmatter(text)
    meta = meta or {}
    target_title = args.text or target.stem.replace("-", " ").replace("_", " ").title()

    # Try to read target title if it exists
    if target.exists():
        tmeta, _ = split_frontmatter(target.read_text(encoding="utf-8"))
        tmeta = tmeta or {}
        target_title = tmeta.get("title") or target_title

    # Preserve original frontmatter text to avoid reformatting timestamps/tags.
    if text.startswith("---"):
        end = text.find("---", 3)
        frontmatter_text = text[: end + 3] if end != -1 else ""
    else:
        frontmatter_text = ""

    # Use a bundle-relative absolute link, the OKF convention documented in
    # SKILL.md (`[text](/path/from/bundle/root)`). Paths are bundle-relative
    # because every command runs from the bundle root.
    link_path = "/" + target.as_posix().lstrip("/")
    link = f"[{target_title}]({link_path})"
    section = "# Related notes\n\n"

    if "# Related notes" in body:
        body = body.rstrip("\n") + f"\n- {link}\n"
    else:
        body = body.rstrip("\n") + "\n\n" + section + f"- {link}\n\n"

    if frontmatter_text:
        source.write_text(frontmatter_text + "\n\n" + body, encoding="utf-8")
    else:
        source.write_text(body, encoding="utf-8")
    print(f"linked: {source} -> {target}")
    return 0


def build_frontmatter(meta: dict[str, Any], flow_style: bool = True) -> str:
    """Serialize frontmatter dict to YAML block.

    Args:
        meta: Frontmatter dictionary.
        flow_style: If True, emit compact inline YAML for lists/dicts
            (e.g. tags: [a, b]). If False, emit block YAML which is more
            human-readable for nested structures.
    """
    require_yaml()
    return "---\n" + yaml.safe_dump(
        meta,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=flow_style,
        width=float("inf"),
    ) + "---\n"


def build_concept_document(
    meta: dict[str, Any],
    body: str = "",
    flow_style: bool = True,
) -> str:
    """Build a full OKF concept document from a complete meta dict and body.

    Args:
        meta: Complete frontmatter dictionary. Must include 'type'.
        body: Markdown body to place after the frontmatter.
        flow_style: YAML style passed to build_frontmatter.

    Returns:
        The full concept document as a string.
    """
    return build_frontmatter(meta, flow_style=flow_style) + "\n" + body


def split_text_frontmatter(text: str) -> tuple[str, str] | None:
    """Return (frontmatter_block_text, body_text) without parsing YAML."""
    if not text.startswith("---"):
        return None
    end = text.find("---", 3)
    if end == -1:
        return None
    return text[: end + 3], text[end + 3 :].lstrip("\n")


def safe_filename(name: str) -> str:
    """Normalize a filename to be safe across filesystems."""
    name = name.lower().strip().replace(" ", "-")
    return re.sub(r"[^a-z0-9_.\-]", "", name)


def cmd_index(args: argparse.Namespace) -> int:
    require_yaml()
    root = Path(".")
    dirs: set[Path] = set()
    for md in root.rglob("*.md"):
        if is_concept(md):
            dirs.add(md.parent)

    for d in sorted(dirs):
        index_path = d / "index.md"
        if index_path.exists() and not args.regenerate:
            continue

        # Preserve an existing frontmatter block (e.g. okf_version on the root
        # index.md) instead of wiping curated content on regenerate.
        existing_frontmatter = ""
        if index_path.exists():
            split = split_text_frontmatter(index_path.read_text(encoding="utf-8"))
            if split is not None:
                existing_frontmatter = split[0] + "\n\n"

        lines = [f"# {d.name or 'Index'}", ""]
        concepts = sorted(p for p in d.iterdir() if is_concept(p))
        for concept in concepts:
            meta, _ = split_frontmatter(concept.read_text(encoding="utf-8"))
            meta = meta or {}
            title = meta.get("title") or concept.stem
            desc = meta.get("description", "")
            lines.append(f"* [{title}]({concept.name}) - {desc}".rstrip(" -"))

        subdirs = sorted(sd for sd in d.iterdir() if sd.is_dir() and any(sd.rglob("*.md")))
        if subdirs:
            lines.extend(["", "# Subdirectories"])
            for sd in subdirs:
                lines.append(f"* [{sd.name}]({sd.name}/)")

        index_path.write_text(
            existing_frontmatter + "\n".join(lines) + "\n", encoding="utf-8"
        )
        print(f"generated: {index_path}")
    return 0


def cmd_check(args: argparse.Namespace) -> int:
    require_yaml()
    root = Path(".")
    warnings = 0
    for md in root.rglob("*.md"):
        if md.name in RESERVED:
            continue
        text = md.read_text(encoding="utf-8")
        meta, body = split_frontmatter(text)
        if meta is None:
            print(f"warn: {md} has no parseable frontmatter")
            warnings += 1
            continue
        if not meta.get("type"):
            print(f"warn: {md} frontmatter missing 'type'")
            warnings += 1

        # Check footnote ids map to sources ids
        source_ids = {s.get("id") for s in meta.get("sources", []) if isinstance(s, dict)}
        for fn in re.findall(r"\[\^([^\]\s]+)\]", body):
            if fn not in source_ids:
                print(f"warn: {md} footnote [^{fn}] has no matching sources[].id")
                warnings += 1

        # Check local image references exist
        for alt, ref in re.findall(r"!\[([^\]]*)\]\(([^)]+)\)", body):
            ref = ref.strip()
            if re.match(r"^[a-z][a-z0-9+.-]*://", ref, re.IGNORECASE):
                continue  # external URL, not checked
            if ref.startswith("/"):
                asset_path = root / ref.lstrip("/")
            else:
                asset_path = md.parent / ref
            if not asset_path.exists():
                print(f"warn: {md} image '{ref}' not found at {asset_path.resolve()}")
                warnings += 1

    if warnings:
        print(f"\n{warnings} warning(s) found. OKF consumers would still tolerate them.")
    else:
        print("OK: bundle looks conformant.")
    return 0


def cmd_log(args: argparse.Namespace) -> int:
    log_path = Path(args.dir) / "log.md" if args.dir else Path("log.md")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    ensure_log_entry(log_path, args.message, args.date)
    print(f"updated: {log_path}")
    return 0


_LINK_RE = re.compile(r"\[([^\]]*)\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")


def _map_link_targets(text: str, mapper: Any) -> str:
    """Rewrite markdown link targets through mapper(target) -> new target | None."""

    def repl(m: re.Match[str]) -> str:
        label, target = m.group(1), m.group(2)
        if re.match(r"^[a-z][a-z0-9+.-]*://", target, re.IGNORECASE):
            return m.group(0)
        new_target = mapper(target)
        if new_target is None:
            return m.group(0)
        return f"[{label}]({new_target})"

    return _LINK_RE.sub(repl, text)


def cmd_move(args: argparse.Namespace) -> int:
    require_yaml()
    src = Path(args.from_path)
    dst = Path(args.to)
    if not src.exists():
        print(f"error: source does not exist: {src}", file=sys.stderr)
        return 1
    if dst.exists():
        print(f"error: destination already exists: {dst}", file=sys.stderr)
        return 1

    src_norm = os.path.normpath(src.as_posix())
    new_abs = "/" + dst.as_posix().lstrip("/")
    old_asset_dir = Path("assets") / src.with_suffix("")
    new_asset_dir = Path("assets") / dst.with_suffix("")
    old_asset_norm = os.path.normpath(str(old_asset_dir))

    dst.parent.mkdir(parents=True, exist_ok=True)
    src.rename(dst)

    # Keep attached media next to the concept: assets/<old-path>/ -> assets/<new-path>/
    asset_moved = False
    if old_asset_dir.exists() and not new_asset_dir.exists():
        new_asset_dir.parent.mkdir(parents=True, exist_ok=True)
        old_asset_dir.rename(new_asset_dir)
        asset_moved = True
    new_asset_norm = os.path.normpath(str(new_asset_dir))

    # Fix relative links inside the moved document (directory depth may change,
    # and its asset directory may have moved with it).
    def fix_own_links(target: str) -> str | None:
        path_part, _, anchor = target.partition("#")
        if not path_part or path_part.startswith("/"):
            return None
        # Links were authored from the old location; resolve there first.
        resolved = os.path.normpath(str(src.parent / path_part))
        if asset_moved and (
            resolved == old_asset_norm
            or resolved.startswith(old_asset_norm + os.sep)
        ):
            resolved = new_asset_norm + resolved[len(old_asset_norm):]
        rel = Path(os.path.relpath(resolved, dst.parent)).as_posix()
        return rel + (f"#{anchor}" if anchor else "")

    dst.write_text(
        _map_link_targets(dst.read_text(encoding="utf-8"), fix_own_links),
        encoding="utf-8",
    )

    # Repoint every bundle-absolute link to the old location at the new one.
    def fix_refs(target: str) -> str | None:
        path_part, _, anchor = target.partition("#")
        suffix = f"#{anchor}" if anchor else ""
        if not path_part:
            return None
        if path_part.startswith("/"):
            if os.path.normpath(path_part.lstrip("/")) == src_norm:
                return new_abs + suffix
            return None
        if os.path.normpath(path_part) == src_norm:
            return new_abs + suffix
        return None

    for md in sorted(Path(".").rglob("*.md")):
        if md == dst or md.name in RESERVED:
            continue
        text = md.read_text(encoding="utf-8")
        new_text = _map_link_targets(text, fix_refs)
        if new_text != text:
            md.write_text(new_text, encoding="utf-8")
            print(f"updated links: {md}")

    # Update directory indexes: drop the old entry, add the new one.
    old_index = src.parent / "index.md"
    if old_index.exists():
        text = old_index.read_text(encoding="utf-8")
        new_text = re.sub(
            r"^.*\]\(" + re.escape(src.name) + r"\).*\n",
            "",
            text,
            flags=re.MULTILINE,
        )
        if new_text != text:
            old_index.write_text(new_text, encoding="utf-8")
            print(f"updated: {old_index}")
    meta, _ = split_frontmatter(dst.read_text(encoding="utf-8"))
    meta = meta or {}
    title = meta.get("title") or dst.stem
    new_index = dst.parent / "index.md"
    update_index(new_index, title=title, rel_path=dst.name,
                 description=meta.get("description", ""))
    print(f"updated: {new_index}")

    log_path = Path("log.md")
    ensure_log_entry(
        log_path,
        f"**Move**: [{title}]({relative_to_log(log_path, dst)}) "
        f"(was {src.as_posix()}).",
    )
    print(f"moved: {src} -> {dst}")
    return 0


def cmd_attach(args: argparse.Namespace) -> int:
    source = Path(args.concept)
    image = Path(args.file)
    if not source.exists():
        print(f"error: concept does not exist: {source}", file=sys.stderr)
        return 1
    if not image.exists():
        print(f"error: image file does not exist: {image}", file=sys.stderr)
        return 1

    text = source.read_text(encoding="utf-8")
    split = split_text_frontmatter(text)
    if split is None:
        print(f"error: {source} has no OKF frontmatter", file=sys.stderr)
        return 1
    frontmatter_text, body = split

    # Decide asset destination: assets/<concept-dir>/<stem>/<filename>
    rel = source.relative_to(Path("."))
    asset_dir = Path("assets") / rel.with_suffix("")
    asset_dir.mkdir(parents=True, exist_ok=True)
    dest_name = safe_filename(image.name)
    dest = asset_dir / dest_name
    # Avoid overwriting by appending a counter
    counter = 1
    stem = dest.stem
    suffix = dest.suffix
    while dest.exists():
        dest = asset_dir / f"{stem}-{counter}{suffix}"
        counter += 1

    shutil.copy2(image, dest)

    # Path from concept file to image (relative for body)
    rel_path = Path(os.path.relpath(dest, source.parent)).as_posix()

    # Bundle-relative absolute path for frontmatter record (stable if doc moves)
    bundle_path = "/" + dest.as_posix()

    # Optionally record asset in frontmatter without reformatting the rest.
    if args.record:
        if bundle_path not in frontmatter_text:
            inner = frontmatter_text[:-3].rstrip("\n")
            lines = inner.splitlines()
            block_idx = next(
                (i for i, line in enumerate(lines) if line.strip() == "assets:"),
                None,
            )
            inline = next(
                (
                    i
                    for i, line in enumerate(lines)
                    if re.match(r"^\s*assets:\s*\[.*\]\s*$", line)
                ),
                None,
            )
            if block_idx is not None:
                lines.insert(block_idx + 1, f"- {bundle_path}")
                inner = "\n".join(lines) + "\n"
            elif inline is not None:
                m = re.match(r"^(\s*assets:\s*)\[(.*)\]\s*$", lines[inline])
                existing_items = m.group(2).strip()
                if existing_items:
                    lines[inline] = f"{m.group(1)}[{existing_items}, {bundle_path}]"
                else:
                    lines[inline] = f"{m.group(1)}[{bundle_path}]"
                inner = "\n".join(lines) + "\n"
            else:
                inner += f"\nassets:\n- {bundle_path}\n"
            frontmatter_text = inner + "---\n"

    caption = args.caption or image.stem.replace("-", " ").replace("_", " ").title()
    image_line = f"![{caption}]({rel_path})\n\n"
    if args.caption:
        image_line += f"*{caption}*\n\n"

    body = body.rstrip("\n") + "\n\n" + image_line
    if frontmatter_text:
        source.write_text(frontmatter_text + "\n\n" + body, encoding="utf-8")
    else:
        source.write_text(body, encoding="utf-8")
    print(f"attached: {dest} -> {source}")
    if args.record:
        print(f"recorded: {bundle_path} in frontmatter assets")
    return 0


def ensure_gitattributes(root: Path, patterns: list[str] | None = None) -> bool:
    """Create or update .gitattributes to route asset patterns through Git LFS.

    Returns True if the file was created or modified, False otherwise.
    """
    patterns = patterns or LFS_PATTERNS
    path = root / ".gitattributes"

    existing_lines: set[str] = set()
    if path.exists():
        existing_text = path.read_text(encoding="utf-8")
        existing_lines = set(existing_text.splitlines())
    else:
        existing_text = ""

    new_lines: list[str] = []
    for pat in patterns:
        line = f"{pat} filter=lfs diff=lfs merge=lfs -text"
        if line not in existing_lines:
            new_lines.append(line)

    if not new_lines:
        return False

    # Preserve existing content and append missing rules.
    text = existing_text
    if text and not text.endswith("\n"):
        text += "\n"
    if LFS_ATTRIBUTES_HEADER.splitlines()[0] not in existing_lines:
        text += LFS_ATTRIBUTES_HEADER
    text += "\n".join(new_lines) + "\n"
    path.write_text(text, encoding="utf-8")
    return True


def cmd_lfs_setup(args: argparse.Namespace) -> int:
    root = Path(args.directory)
    if not root.exists():
        print(f"error: directory does not exist: {root}", file=sys.stderr)
        return 1
    modified = ensure_gitattributes(root, LFS_PATTERNS)
    if modified:
        print(f"updated: {root / '.gitattributes'}")
    else:
        print(f"up-to-date: {root / '.gitattributes'}")
    return 0


def cmd_init(args: argparse.Namespace) -> int:
    root = Path(args.directory)
    root.mkdir(parents=True, exist_ok=True)
    name = args.name or root.name or "Notes"

    subdirs = ["topics", "references", "computations"]
    for sub in subdirs:
        (root / sub).mkdir(exist_ok=True)

    # Root index.md with okf_version frontmatter.
    root_index = root / "index.md"
    if not root_index.exists():
        root_index.write_text(
            f"""---
okf_version: "0.2"
---

# {name}

A learning-note bundle in the Open Knowledge Format (OKF) v0.2.

# Directories

* [topics](topics/) - thematic learning notes.
* [references](references/) - external-source mirrors and citations.
* [computations](computations/) - reproducible formulas, code, and attested computations.

# Update Log

See [log.md](log.md) for the history of changes.
""",
            encoding="utf-8",
        )
        print(f"created: {root_index}")

    # Root log.md.
    root_log = root / "log.md"
    if not root_log.exists():
        root_log.write_text(
            "# Update Log\n\n"
            f"## {now_iso()[:10]}\n"
            "* **Initialization**: Created the OKF note bundle.\n",
            encoding="utf-8",
        )
        print(f"created: {root_log}")

    # Per-subdirectory indexes.
    for sub in subdirs:
        idx = root / sub / "index.md"
        if not idx.exists():
            idx.write_text(
                f"# {sub.title()}\n\n"
                "_This index will be populated automatically as concepts are added._\n\n",
                encoding="utf-8",
            )
            print(f"created: {idx}")

    # Git LFS support for assets.
    if not args.no_lfs:
        if ensure_gitattributes(root, LFS_PATTERNS):
            print(f"created: {root / '.gitattributes'}")
        else:
            print(f"up-to-date: {root / '.gitattributes'}")

    print(f"initialized OKF bundle: {root.resolve()}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="OKF note-taking helper")
    sub = parser.add_subparsers(dest="command", required=True)

    new = sub.add_parser("new", help="create a new OKF concept note")
    new.add_argument("path")
    new.add_argument("--title", default=None)
    new.add_argument("--description", default=None)
    new.add_argument("--type", default="Note")
    new.add_argument("--tags", nargs="+", default=None)
    new.set_defaults(func=cmd_new)

    link = sub.add_parser("link", help="add a bundle-relative link between notes")
    link.add_argument("from_path")
    link.add_argument("--to", required=True)
    link.add_argument("--text", default=None)
    link.set_defaults(func=cmd_link)

    mv = sub.add_parser("move", help="move or rename a concept note and fix links")
    mv.add_argument("from_path")
    mv.add_argument("to")
    mv.set_defaults(func=cmd_move)

    idx = sub.add_parser("index", help="generate or update index.md files")
    idx.add_argument("--regenerate", action="store_true")
    idx.set_defaults(func=cmd_index)

    check = sub.add_parser("check", help="check bundle conformance")
    check.set_defaults(func=cmd_check)

    log = sub.add_parser("log", help="append an entry to a log.md")
    log.add_argument("message")
    log.add_argument("--dir", default=None)
    log.add_argument("--date", default=None)
    log.set_defaults(func=cmd_log)

    init = sub.add_parser("init", help="create an empty OKF bundle skeleton")
    init.add_argument("directory", nargs="?", default=".", help="bundle root directory")
    init.add_argument("--name", default=None, help="bundle display name")
    init.add_argument("--no-lfs", action="store_true", help="skip creating .gitattributes for Git LFS")
    init.set_defaults(func=cmd_init)

    lfs = sub.add_parser("lfs-setup", help="create or update .gitattributes for Git LFS")
    lfs.add_argument("directory", nargs="?", default=".", help="bundle root directory")
    lfs.set_defaults(func=cmd_lfs_setup)

    attach = sub.add_parser("attach", help="attach an image to a concept")
    attach.add_argument("concept", help="path to the concept markdown file")
    attach.add_argument("--file", required=True, help="path to the image file")
    attach.add_argument("--caption", default=None, help="image caption / alt text")
    attach.add_argument("--record", action="store_true", help="record asset path in frontmatter")
    attach.set_defaults(func=cmd_attach)

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
